#pragma once

#undef RGB_MATRIX_DEFAULT_MODE
#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#define DEF_MODE RGB_MATRIX_TYPING_HEATMAP
#define CMK_MODE RGB_MATRIX_TYPING_HEATMAP

// Indicator flags
#ifdef RGBLIGHT_ENABLE
#    define CAP_FLAG LED_FLAG_UNDERGLOW
#    define MOD_FLAG LED_FLAG_UNDERGLOW
#else
#    define CAP_FLAG LED_FLAG_ALL
#    define MOD_FLAG LED_FLAG_MODIFIER
#endif

#ifdef BKB_LAYOUT
#define RGB_MODS RGB_GOLDENROD
#define RGB_SYM RGB_RED
#define RGB_NUM RGB_PINK
#define RGB_FNC RGB_BLUE
#define RGB_PNT RGB_GREEN
#define HSV_PNT HSV_GREEN
#define RGB_NAV RGB_ORANGE
#define RGB_MED RGB_MAGENTA
#else
#define RGB_MODS RGB_GOLDENROD
#define RGB_SYM RGB_SPRINGGREEN
#define RGB_NUM RGB_ORANGE
#define RGB_FNC RGB_MAGENTA
#define RGB_PNT RGB_GREEN
#define HSV_PNT HSV_GREEN
#endif
